name: chat-app
services:
  page:
    image: chat-page
    build: service-page
    ports:
    - "3000:80"
    
  socket:
    image: chat-socket
    build: service-socket
    environment:
    - DATABASE_URI=database
    ports:
    - "8000:3000"

  database:
    image: mongo