name: chat-app
services:
  page:
    image: chat-page
    build: service-page
    environment:
    - SOCKET_URI=localhost:8000
    ports:
    - "3000:80"
    depends_on:
    - socket
    
  socket:
    image: chat-socket
    build: service-socket
    environment:
    - DATABASE_URI=database
    - BUCKET=micro-chat-bucket
    ports:
    - "8000:3000"
    depends_on:
    - database

  database:
    image: mongo