name: chat-app
services:
  page:
    image: chat-page
    build: service-page
    environment:
    - SOCKET_URI=socket
    ports:
    - "3000:80"
    
  socket:
    image: chat-socket
    build: service-socket
    environment:
    - DATABASE_CONN=database
    - PROJECT=micro-chat-382821
    - CREDENTIALS=./google-key.json
    - BUCKET_NAME=micro-chat-bucket
    ports:
    - "8000:3000"

  database:
    image: mongo