name: chat-app
services:
  page:
    image: chat-page
    build: service-page
    ports:
    - "3000:80"

  api:
    image: chat-api
    build: service-api
    ports:
    - "8001:3000"
    
  socket:
    image: chat-socket
    build: service-socket
    ports:
    - "8000:3000"

  database:
    image: mongo