name: 'Trigger on push to main'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Storing Google credentials to json file'
        shell: bash
        env:
          GOOGLE_AUTH_CONFIG: ${{ secrets.GOOGLE_AUTH_CONFIG }}
        run: echo $GOOGLE_AUTH_CONFIG > google-key.json

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push the page service image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: service-page
          tags: ${{secrets.DOCKER_USERNAME}}/microchatpage:latest

      - name: Build and push the socket service image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: service-socket
          tags: ${{secrets.DOCKER_USERNAME}}/microchatsocket:latest

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan
      
      - name: Terraform apply
        run: terraform apply --auto-approve