name: 'Trigger on push to main'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the page service image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:service-page"
          push: true
          tags: danielcarreira/microchatpage:latest

      - name: Build and push the socket service image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:service-socket"
          push: true
          tags: danielcarreira/microchatsocket:latest

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform init
        run: terraform init
      
      - name: Terraform apply
        run: terraform apply --auto-approve 