name: 'Trigger on push to main'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Storing Google credentials to json file'
        run: echo ${{ secrets.GOOGLE_AUTH_CONFIG }} | base64 -d > google-key.json
        shell: bash

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push the page service image
        uses: docker/build-push-action@v2
        with:
          context: client
          file: service-page/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/microchatpage:latest
        env:
          ENV_VAR_1: value1
          ENV_VAR_2: value2

      - name: Build and push the socket service image
        uses: docker/build-push-action@v2
        with:
          context: client
          file: service-socket/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/microchatsocket:latest

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan
      
      - name: Terraform apply
        run: terraform apply --auto-approve